# Generated by ChatGPT on 2026-01-05
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("user_create", "إنشاء مستخدم"), ("user_update", "تحديث مستخدم"), ("user_disable", "تعطيل مستخدم"), ("user_enable", "تفعيل مستخدم"), ("role_change", "تغيير دور"), ("scope_change", "تغيير نطاق (منطقة/جهة)"), ("password_reset", "إعادة تعيين كلمة مرور")], db_index=True, max_length=32, verbose_name="الإجراء")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="عنوان IP")),
                ("user_agent", models.CharField(blank=True, default="", max_length=256, verbose_name="User-Agent")),
                ("before", models.JSONField(blank=True, null=True, verbose_name="قبل")),
                ("after", models.JSONField(blank=True, null=True, verbose_name="بعد")),
                ("note", models.CharField(blank=True, default="", max_length=250, verbose_name="ملاحظة")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_actor_logs", to=settings.AUTH_USER_MODEL, verbose_name="المنفذ")),
                ("target_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_target_logs", to=settings.AUTH_USER_MODEL, verbose_name="المستخدم المستهدف")),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action", "created_at"], name="sysadmin_au_action_9bb2f1_idx"),
        ),
    ]
