# Generated by Django 6.0 on 2026-01-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='sysadmin_au_action_763a7b_idx',
            old_name='sysadmin_au_action_9bb2f1_idx',
        ),
    ]
