# Generated by Django 6.0 on 2026-01-02 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
        ('organizations', '0002_alter_organizationbranch_options_and_more'),
        ('regions', '0002_alter_region_options_alter_region_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'verbose_name': 'فرد', 'verbose_name_plural': 'الأفراد'},
        ),
        migrations.AlterField(
            model_name='individual',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='الرقم الوظيفي (اختياري)'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='رقم الهوية (اختياري)'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='org_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individuals', to='organizations.organizationbranch', verbose_name='فرع الجهة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individuals', to='regions.region', verbose_name='المنطقة'),
        ),
    ]
