# Generated by Django 6.0 on 2026-01-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainerprofile_delete_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='region',
        ),
    ]
