# Generated by Django 6.0 on 2026-01-05 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدير عام'), ('region_manager', 'مدير إدارة منطقة'), ('supervisor', 'مشرف (نائب)'), ('coordinator', 'منسق الدورات'), ('trainer', 'مدرب'), ('org_rep', 'ممثل جهة'), ('individual', 'فرد')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='permissionrequest',
            index=models.Index(fields=['status', 'created_at'], name='iam_permiss_status_8e5fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='iam_roleper_role_998e66_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'permission'], name='iam_userper_user_id_a6d340_idx'),
        ),
    ]
