# Generated by Django 6.0 on 2026-01-02 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'بانتظار الاعتماد'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('suspended', 'موقوف')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_org_branches', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_branches', to='regions.region')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organizations.organizationmaster')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='organizations.organizationbranch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_representative', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='organizationbranch',
            index=models.Index(fields=['region', 'status'], name='organizatio_region__499ab1_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationbranch',
            constraint=models.UniqueConstraint(fields=('master', 'region'), name='unique_master_region_branch'),
        ),
        migrations.AddIndex(
            model_name='organizationrepresentative',
            index=models.Index(fields=['org_branch', 'is_primary'], name='organizatio_org_bra_ecb3b7_idx'),
        ),
    ]
