# Generated by Django 6.0 on 2026-01-02 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('regions', '0002_alter_region_options_alter_region_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationbranch',
            options={'verbose_name': 'فرع جهة', 'verbose_name_plural': 'فروع الجهات'},
        ),
        migrations.AlterModelOptions(
            name='organizationmaster',
            options={'verbose_name': 'جهة أم', 'verbose_name_plural': 'الجهات الأم'},
        ),
        migrations.AlterModelOptions(
            name='organizationrepresentative',
            options={'verbose_name': 'ممثل جهة', 'verbose_name_plural': 'ممثلو الجهات'},
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_org_branches', to=settings.AUTH_USER_MODEL, verbose_name='تم الاعتماد بواسطة'),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الفرع (اختياري)'),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organizations.organizationmaster', verbose_name='الجهة الأم'),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='هاتف الفرع'),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_branches', to='regions.region', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='status',
            field=models.CharField(choices=[('pending', 'بانتظار الاعتماد'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('suspended', 'موقوف')], db_index=True, default='pending', max_length=20, verbose_name='حالة الاعتماد'),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='اسم الجهة الأم'),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='رقم/معرف الجهة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='organizationrepresentative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='organizationrepresentative',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='ممثل أساسي'),
        ),
        migrations.AlterField(
            model_name='organizationrepresentative',
            name='org_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='organizations.organizationbranch', verbose_name='فرع الجهة'),
        ),
        migrations.AlterField(
            model_name='organizationrepresentative',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_representative', to=settings.AUTH_USER_MODEL, verbose_name='حساب ممثل الجهة'),
        ),
    ]
