# Generated by Django 6.0 on 2026-01-02 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('courses', '0002_alter_course_options_alter_coursesession_options_and_more'),
        ('regions', '0002_alter_region_options_alter_region_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'شهادة', 'verbose_name_plural': 'الشهادات'},
        ),
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'verbose_name': 'قالب شهادة', 'verbose_name_plural': 'قوالب الشهادات'},
        ),
        migrations.AlterModelOptions(
            name='certificateverification',
            options={'verbose_name': 'تحقق شهادة', 'verbose_name_plural': 'التحقق من الشهادات'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment', verbose_name='تسجيل الدورة'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='أُصدرت بواسطة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='رقم تسلسلي'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatetemplate', verbose_name='القالب (اختياري)'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(max_length=120, verbose_name='اسم القالب'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_templates', to='regions.region', verbose_name='المنطقة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='certificateverification',
            name='certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='certificates.certificate', verbose_name='الشهادة'),
        ),
        migrations.AlterField(
            model_name='certificateverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='certificateverification',
            name='public_lookup_enabled',
            field=models.BooleanField(default=True, verbose_name='إتاحة التحقق العام'),
        ),
        migrations.AlterField(
            model_name='certificateverification',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='رمز التحقق'),
        ),
    ]
