# Generated by Django 6.0 on 2026-01-02 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('individuals', '0001_initial'),
        ('organizations', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='individuals.individual'),
        ),
        migrations.AddField(
            model_name='user',
            name='org_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.organizationbranch'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='regions.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'purpose', 'is_used'], name='accounts_em_email_5d1e85_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['expires_at'], name='accounts_em_expires_2be763_idx'),
        ),
    ]
