# Generated by Django 6.0 on 2026-01-02 20:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('individuals', '0001_initial'),
        ('organizations', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'verbose_name': 'رمز تحقق عبر البريد', 'verbose_name_plural': 'رموز التحقق عبر البريد'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(db_index=True, max_length=10, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='ينتهي في'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='تم استخدامه'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'تسجيل الدخول'), ('verify_email', 'تفعيل البريد'), ('reset_password', 'استعادة كلمة المرور')], default='login', max_length=20, verbose_name='الغرض'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='individuals.individual', verbose_name='ملف الفرد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='org_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.organizationbranch', verbose_name='فرع الجهة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بصيغة دولية مثل +9665xxxxxxxx', regex='^\\+?\\d{8,15}$')], verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='regions.region', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدير عام'), ('region_manager', 'مدير إدارة منطقة'), ('supervisor', 'مشرف (نائب)'), ('coordinator', 'منسق الدورات'), ('org_rep', 'ممثل جهة'), ('individual', 'فرد')], db_index=True, default='individual', max_length=32, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='اختياري (لا نعتمد عليه للدخول).', max_length=150, null=True, verbose_name='اسم المستخدم'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
    ]
