# Generated by Django 6.0 on 2026-01-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_individualprofile_organizationprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدير عام'), ('region_manager', 'مدير إدارة منطقة'), ('supervisor', 'مشرف (نائب)'), ('coordinator', 'منسق الدورات'), ('trainer', 'مدرب'), ('org_rep', 'ممثل جهة'), ('individual', 'فرد')], db_index=True, default='individual', max_length=32, verbose_name='الدور'),
        ),
    ]
