# Generated by Django 6.0 on 2026-01-02 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_region_options_alter_region_code_and_more'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'verbose_name': 'تذكرة دعم', 'verbose_name_plural': 'تذاكر الدعم'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'verbose_name': 'مرفق تذكرة', 'verbose_name_plural': 'مرفقات التذاكر'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'verbose_name': 'رسالة تذكرة', 'verbose_name_plural': 'رسائل التذاكر'},
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='مسندة إلى (اختياري)'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('account', 'الحساب'), ('courses', 'الدورات'), ('certificates', 'الشهادات'), ('organizations', 'الجهات'), ('technical', 'تقني'), ('other', 'أخرى')], db_index=True, default='technical', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=models.TextField(verbose_name='وصف المشكلة'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='escalation_level',
            field=models.PositiveIntegerField(default=0, verbose_name='مستوى التصعيد'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع'), ('urgent', 'عاجل')], db_index=True, default='medium', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='regions.region', verbose_name='المنطقة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('waiting_user', 'بانتظار المستخدم'), ('escalated', 'مصعد'), ('resolved', 'محلول'), ('closed', 'مغلق')], db_index=True, default='open', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان التذكرة'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='اسم الملف'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file_path',
            field=models.CharField(max_length=500, verbose_name='مسار الملف'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportticket', verbose_name='التذكرة'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='رُفع بواسطة'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket', verbose_name='التذكرة'),
        ),
    ]
