# Generated by Django 6.0 on 2026-01-02 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individuals', '0001_initial'),
        ('organizations', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('delivery_mode', models.CharField(choices=[('in_person', 'حضوري'), ('online', 'عن بعد'), ('hybrid', 'مختلط')], default='in_person', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('allow_individuals', models.BooleanField(default=True)),
                ('allow_organizations', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='regions.region')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('individual_self', 'تسجيل فردي'), ('org_request', 'طلب جهة')], default='individual_self', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'بانتظار'), ('accepted', 'مقبول'), ('waitlist', 'قائمة انتظار'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='individuals.individual')),
            ],
        ),
        migrations.CreateModel(
            name='OrgCourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('processed', 'تمت المعالجة'), ('cancelled', 'ملغي')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_requests', to='courses.course')),
                ('org_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to='organizations.organizationbranch')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_course_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgCourseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_request_item', to='courses.enrollment')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_request_items', to='individuals.individual')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.orgcourserequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['region', 'is_published', 'start_at'], name='courses_cou_region__ced9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='courses_enr_course__78d524_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['individual', 'status'], name='courses_enr_individ_4281f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course', 'individual'), name='unique_enrollment_course_individual'),
        ),
        migrations.AddIndex(
            model_name='orgcourserequest',
            index=models.Index(fields=['org_branch', 'course', 'status'], name='courses_org_org_bra_fdf6a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgcourserequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'individual'), name='unique_request_item_individual'),
        ),
    ]
