# Generated by Django 6.0 on 2026-01-02 20:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('individuals', '0002_alter_individual_options_alter_individual_created_at_and_more'),
        ('organizations', '0002_alter_organizationbranch_options_and_more'),
        ('regions', '0002_alter_region_options_alter_region_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-start_at'], 'verbose_name': 'دورة', 'verbose_name_plural': 'الدورات'},
        ),
        migrations.AlterModelOptions(
            name='coursesession',
            options={'verbose_name': 'جلسة دورة', 'verbose_name_plural': 'جلسات الدورات'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'تسجيل دورة', 'verbose_name_plural': 'تسجيلات الدورات'},
        ),
        migrations.AlterModelOptions(
            name='orgcourserequest',
            options={'verbose_name': 'طلب جهة لدورة', 'verbose_name_plural': 'طلبات الجهات للدورات'},
        ),
        migrations.AlterModelOptions(
            name='orgcourserequestitem',
            options={'verbose_name': 'عنصر طلب جهة', 'verbose_name_plural': 'عناصر طلبات الجهات'},
        ),
        migrations.AlterField(
            model_name='course',
            name='allow_individuals',
            field=models.BooleanField(default=True, verbose_name='السماح للأفراد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='allow_organizations',
            field=models.BooleanField(default=True, verbose_name='السماح للجهات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='delivery_mode',
            field=models.CharField(choices=[('in_person', 'حضوري'), ('online', 'عن بعد'), ('hybrid', 'مختلط')], default='in_person', max_length=20, verbose_name='نوع التنفيذ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الدورة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_at',
            field=models.DateTimeField(verbose_name='تاريخ/وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منشورة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='regions.region', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_at',
            field=models.DateTimeField(verbose_name='تاريخ/وقت البداية'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=220, verbose_name='عنوان الدورة'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='end_at',
            field=models.DateTimeField(verbose_name='نهاية الجلسة'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='start_at',
            field=models.DateTimeField(verbose_name='بداية الجلسة'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان الجلسة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='individuals.individual', verbose_name='الفرد'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('individual_self', 'تسجيل فردي'), ('org_request', 'طلب جهة')], default='individual_self', max_length=30, verbose_name='مصدر التسجيل'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'بانتظار'), ('accepted', 'مقبول'), ('waitlist', 'قائمة انتظار'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], db_index=True, default='pending', max_length=20, verbose_name='حالة التسجيل'),
        ),
        migrations.AlterField(
            model_name='orgcourserequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_requests', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='orgcourserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='orgcourserequest',
            name='org_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to='organizations.organizationbranch', verbose_name='فرع الجهة'),
        ),
        migrations.AlterField(
            model_name='orgcourserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_course_requests', to=settings.AUTH_USER_MODEL, verbose_name='مطلوب بواسطة'),
        ),
        migrations.AlterField(
            model_name='orgcourserequest',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('processed', 'تمت المعالجة'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='orgcourserequestitem',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_request_item', to='courses.enrollment', verbose_name='التسجيل الناتج (اختياري)'),
        ),
        migrations.AlterField(
            model_name='orgcourserequestitem',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_request_items', to='individuals.individual', verbose_name='الفرد'),
        ),
        migrations.AlterField(
            model_name='orgcourserequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.orgcourserequest', verbose_name='الطلب'),
        ),
    ]
