# Generated by Django 6.0 on 2026-01-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'منطقة', 'verbose_name_plural': 'المناطق'},
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رمز المنطقة'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='اسم المنطقة'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
    ]
