"""
Django settings for thqaf project.
Generated by 'django-admin startproject' using Django 6.0
"""

from pathlib import Path
import os

# -------------------------------------------------------------------
# Base directory
# -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------------------------------------------
# Security & Debug
# -------------------------------------------------------------------
# ⚠️ في الإنتاج: لا تترك SECRET_KEY هنا، اجعله من متغيرات بيئة
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-1#w619z9abbri!$*cg1cq58c!q)qhy^$&0aa*27ap4l-c)2l!%",
)

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split() if not DEBUG else []


# -------------------------------------------------------------------
# Application definition
# -------------------------------------------------------------------
INSTALLED_APPS = [
    # Django default
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Platform apps
    "accounts",
    "regions",
    "organizations",
    "individuals",
    "courses",
    "attendance",
    "certificates",
    "support",
    "contact",
]

# Custom User Model
AUTH_USER_MODEL = "accounts.User"


# -------------------------------------------------------------------
# Middleware
# -------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# -------------------------------------------------------------------
# URLs & WSGI
# -------------------------------------------------------------------
ROOT_URLCONF = "thqaf.urls"
WSGI_APPLICATION = "thqaf.wsgi.application"


# -------------------------------------------------------------------
# Templates
# -------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "templates/accounts_temp",
            BASE_DIR / "templates/regions_temp",
            BASE_DIR / "templates/organizations_temp",
            BASE_DIR / "templates/individuals_temp",
            BASE_DIR / "templates/courses_temp",
            BASE_DIR / "templates/attendance_temp",
            BASE_DIR / "templates/certificates_temp",
            BASE_DIR / "templates/support_temp",
            BASE_DIR / "templates/contact_temp",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# -------------------------------------------------------------------
# Database
# -------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# -------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# -------------------------------------------------------------------
# Internationalization
# -------------------------------------------------------------------
LANGUAGE_CODE = "ar"
TIME_ZONE = "Asia/Riyadh"
USE_I18N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# -------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# -------------------------------------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"


# -------------------------------------------------------------------
# Media files (Uploads)
# -------------------------------------------------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# -------------------------------------------------------------------
# Authentication URLs
# -------------------------------------------------------------------
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# -------------------------------------------------------------------
# Email (Hostinger SMTP) - ✅ آمن عبر متغيرات بيئة
# -------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("THQAF_EMAIL_HOST", "smtp.hostinger.com")
EMAIL_PORT = int(os.getenv("THQAF_EMAIL_PORT", "465"))
EMAIL_HOST_USER = os.getenv("THQAF_EMAIL_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("THQAF_EMAIL_PASSWORD", "")

# Hostinger عادة SSL 465
EMAIL_USE_SSL = os.getenv("THQAF_EMAIL_USE_SSL", "True").lower() in ("1", "true", "yes")
EMAIL_USE_TLS = os.getenv("THQAF_EMAIL_USE_TLS", "False").lower() in ("1", "true", "yes")

# اسم المرسل
THQAF_EMAIL_FROM_NAME = os.getenv("THQAF_EMAIL_FROM_NAME", "بوابة ثقف")
DEFAULT_FROM_EMAIL = f"{THQAF_EMAIL_FROM_NAME} <{EMAIL_HOST_USER}>"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# مهلة إرسال (اختياري)
EMAIL_TIMEOUT = int(os.getenv("THQAF_EMAIL_TIMEOUT", "15"))


# -------------------------------------------------------------------
# Security headers (مفيدة الآن + للإنتاج لاحقًا)
# -------------------------------------------------------------------
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

# Cookies (في الإنتاج: اجعلها True مع HTTPS)
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"


# -------------------------------------------------------------------
# Logging (اختياري ومفيد للتتبع)
# -------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO" if DEBUG else "WARNING",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.core.mail": {
            "handlers": ["console"],
            "level": "INFO" if DEBUG else "WARNING",
            "propagate": False,
        },
    },
}


# -------------------------------------------------------------------
# Default primary key field type
# -------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
