# Generated by Django 6.0 on 2026-01-02 20:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0002_alter_course_options_alter_coursesession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceconfirmation',
            options={'verbose_name': 'تأكيد حضور', 'verbose_name_plural': 'تأكيدات الحضور'},
        ),
        migrations.AlterField(
            model_name='attendanceconfirmation',
            name='confirmation_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='رمز التأكيد (اختياري)'),
        ),
        migrations.AlterField(
            model_name='attendanceconfirmation',
            name='confirmed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التأكيد'),
        ),
        migrations.AlterField(
            model_name='attendanceconfirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='attendanceconfirmation',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_confirmation', to='courses.enrollment', verbose_name='تسجيل الدورة'),
        ),
        migrations.AlterField(
            model_name='attendanceconfirmation',
            name='method',
            field=models.CharField(choices=[('self_confirm', 'تأكيد ذاتي'), ('code', 'رمز حضور'), ('qr', 'QR')], default='self_confirm', max_length=20, verbose_name='طريقة التأكيد'),
        ),
        migrations.AlterField(
            model_name='attendanceconfirmation',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة'),
        ),
    ]
